version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: boookntalk-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: espoir
      POSTGRES_PASSWORD: espoir123sec
      POSTGRES_DB: boookntalk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
